name: Security Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security-scan:
    name: Run Security Tools
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    ##############################################
    # CodeQL Analysis
    ##############################################
    - name: Set up CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'ruby, python, csharp, bash'

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
      with:
        output: results/codeql.sarif

    ##############################################
    # Semgrep Analysis
    ##############################################
    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep --config "p/ci" --output results/semgrep-results.sarif --sarif .

    ##############################################
    # Snyk Analysis
    ##############################################
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Open Source Scan
      run: snyk test --json-file-output=results/snyk-open-source.json

    - name: Snyk Code Analysis
      run: snyk code test --json-file-output=results/snyk-code.json

    ##############################################
    # Upload SARIF results for Code Scanning
    ##############################################
    - name: Upload SARIF Results (CodeQL and Semgrep)
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: |
          results/codeql.sarif
          results/semgrep-results.sarif

    ##############################################
    # Publish Results (Optional, for Snyk)
    ##############################################
    - name: Upload Snyk Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-results
        path: |
          results/snyk-open-source.json
          results/snyk-code.json
