name: Snyk Code Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk-code-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 3: Authenticate with Snyk
      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      # Step 4: Run Snyk Code Analysis
      - name: Run Snyk Code Analysis
        env:
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
        run: snyk code test --org=$SNYK_ORG_ID --sarif --json-file-output=snyk-code-results.sarif

      # Step 5: Upload SARIF file to GitHub Security tab (optional)
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code-results.sarif
