name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if required for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Snyk CLI
      - name: Install Snyk CLI
        uses: snyk/actions/setup@v2
        with:
          version: 'latest'
          # Pass the API token securely
          token: ${{ secrets.SNYK_TOKEN }}

      # Step 4: Run Snyk tests
      - name: Test for vulnerabilities
        run: |
          snyk test --org=${{ secrets.SNYK_ORG_ID }}
          snyk code test --org=${{ secrets.SNYK_ORG_ID }}

      - name: Generate and upload SARIF report
        run: snyk code test --org=${{ secrets.SNYK_ORG_ID }} --sarif --json-file-output=snyk-code-results.sarif
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code-results.sarif
